apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  labels:
    app: api_server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api_server
  template:
    metadata:
      labels:
        app: api_server
    spec:
      containers:
      - name: client 
        image: ghcr.io/kr-0-n/master_thesis/api_server:latest
        ports:
        - containerPort: 50051
      nodeSelector: 
        "kubernetes.io/hostname": "manager-0"
      imagePullSecrets:
      - name: regcred
    
