replicaCount: 2
env:
  BANDWIDTH: "300K" #use K for kbits, M for Mbits. Omit letter for bits
  LATENCY: "20"

server:
  CPU: "2000m"
  MEM: "1000Mi"
  labels:
    feature: gpu

client:
  CPU: "1000m"
  MEM: "1000Mi"
