// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: proto/message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LinkInfoMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Latency       int32                  `protobuf:"varint,3,opt,name=latency,proto3" json:"latency,omitempty"`
	Throughput    float64                `protobuf:"fixed64,4,opt,name=throughput,proto3" json:"throughput,omitempty"`
	Timestamp     *int32                 `protobuf:"varint,5,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkInfoMessage) Reset() {
	*x = LinkInfoMessage{}
	mi := &file_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkInfoMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkInfoMessage) ProtoMessage() {}

func (x *LinkInfoMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkInfoMessage.ProtoReflect.Descriptor instead.
func (*LinkInfoMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *LinkInfoMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *LinkInfoMessage) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *LinkInfoMessage) GetLatency() int32 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *LinkInfoMessage) GetThroughput() float64 {
	if x != nil {
		return x.Throughput
	}
	return 0
}

func (x *LinkInfoMessage) GetTimestamp() int32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

type LinkInfoMessageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*LinkInfoMessage     `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkInfoMessageList) Reset() {
	*x = LinkInfoMessageList{}
	mi := &file_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkInfoMessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkInfoMessageList) ProtoMessage() {}

func (x *LinkInfoMessageList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkInfoMessageList.ProtoReflect.Descriptor instead.
func (*LinkInfoMessageList) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *LinkInfoMessageList) GetLinks() []*LinkInfoMessage {
	if x != nil {
		return x.Links
	}
	return nil
}

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_proto_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{2}
}

var File_proto_message_proto protoreflect.FileDescriptor

const file_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x13proto/message.proto\x12\x05links\"\xa0\x01\n" +
	"\x0fLinkInfoMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x18\n" +
	"\alatency\x18\x03 \x01(\x05R\alatency\x12\x1e\n" +
	"\n" +
	"throughput\x18\x04 \x01(\x01R\n" +
	"throughput\x12!\n" +
	"\ttimestamp\x18\x05 \x01(\x05H\x00R\ttimestamp\x88\x01\x01B\f\n" +
	"\n" +
	"_timestamp\"C\n" +
	"\x13LinkInfoMessageList\x12,\n" +
	"\x05links\x18\x01 \x03(\v2\x16.links.LinkInfoMessageR\x05links\"\x0e\n" +
	"\fEmptyMessage2\x8a\x01\n" +
	"\vLinkService\x129\n" +
	"\bSendData\x12\x16.links.LinkInfoMessage\x1a\x13.links.EmptyMessage\"\x00\x12@\n" +
	"\vGetAllLinks\x12\x13.links.EmptyMessage\x1a\x1a.links.LinkInfoMessageList\"\x00B\n" +
	"Z\b./;protob\x06proto3"

var (
	file_proto_message_proto_rawDescOnce sync.Once
	file_proto_message_proto_rawDescData []byte
)

func file_proto_message_proto_rawDescGZIP() []byte {
	file_proto_message_proto_rawDescOnce.Do(func() {
		file_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)))
	})
	return file_proto_message_proto_rawDescData
}

var file_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_message_proto_goTypes = []any{
	(*LinkInfoMessage)(nil),     // 0: links.LinkInfoMessage
	(*LinkInfoMessageList)(nil), // 1: links.LinkInfoMessageList
	(*EmptyMessage)(nil),        // 2: links.EmptyMessage
}
var file_proto_message_proto_depIdxs = []int32{
	0, // 0: links.LinkInfoMessageList.links:type_name -> links.LinkInfoMessage
	0, // 1: links.LinkService.SendData:input_type -> links.LinkInfoMessage
	2, // 2: links.LinkService.GetAllLinks:input_type -> links.EmptyMessage
	2, // 3: links.LinkService.SendData:output_type -> links.EmptyMessage
	1, // 4: links.LinkService.GetAllLinks:output_type -> links.LinkInfoMessageList
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_message_proto_init() }
func file_proto_message_proto_init() {
	if File_proto_message_proto != nil {
		return
	}
	file_proto_message_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_message_proto_goTypes,
		DependencyIndexes: file_proto_message_proto_depIdxs,
		MessageInfos:      file_proto_message_proto_msgTypes,
	}.Build()
	File_proto_message_proto = out.File
	file_proto_message_proto_goTypes = nil
	file_proto_message_proto_depIdxs = nil
}
